import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import Header from '@/components/Header';
import { ThemeProvider } from './theme-provider';
import Responsive from '@/components/Responsive';
import SideBar from '@/components/Sidebar';
import AuthContext from '@/context/AuthContext';
import Chat from '@/components/Chat';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="App">
      <body className={inter.className}>
        <AuthContext>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <Responsive>
                <Header></Header>
                {children}
                <SideBar />
                <Chat></Chat>
              </Responsive>
            </Providers>
          </ThemeProvider>
        </AuthContext>
      </body>
    </html>
  );
}
